name = input ("Enter you Name\n")
surname = input ("Enter you Surname\n")
year = input("Enter you Year\n")
code = input("Emter your Student code\n")
print("Name : %s" %name)
print("Surname : %s" %surname)
print("Year : %s" %year)
print("Student : %s" %code)
